# Dockerfile reference:
# https://docs.docker.com/engine/reference/builder/

# Dockerfile best practice:
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/

# Use an official node runtime as a base image
FROM node:boron-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install all packages in package.json
RUN npm install pm2 -g
RUN npm install --production

# Make ports available to the world outside this container
# 80: http
EXPOSE 80

# Run npm start when the container launches
CMD ["pm2-docker", "server.js"]
